workflows:
  liquid-glass-demo:
    name: Liquid Glass Demo (iOS 26)
    max_build_duration: 30
    instance_type: mac_mini_m2
    
    environment:
      xcode: 26.1
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
      cancel_previous_builds: true
    
    scripts:
      - name: Show Xcode version
        script: |
          xcodebuild -version
          xcodebuild -showsdks
      
      - name: Build iOS App
        script: |
          cd LiquidGlassDemo
          xcodebuild build \
            -project LiquidGlassDemo.xcodeproj \
            -scheme LiquidGlassDemo \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      
      - name: Archive App
        script: |
          cd LiquidGlassDemo
          xcodebuild archive \
            -project LiquidGlassDemo.xcodeproj \
            -scheme LiquidGlassDemo \
            -destination 'generic/platform=iOS' \
            -archivePath build/LiquidGlassDemo.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SKIP_INSTALL=NO
      
      - name: Export Unsigned IPA
        script: |
          cd LiquidGlassDemo/build
          mkdir -p Payload
          cp -r LiquidGlassDemo.xcarchive/Products/Applications/LiquidGlassDemo.app Payload/
          zip -r LiquidGlassDemo-unsigned.ipa Payload
    
    artifacts:
      - LiquidGlassDemo/build/LiquidGlassDemo-unsigned.ipa
      - LiquidGlassDemo/build/LiquidGlassDemo.xcarchive

  flutter-app-ios26:
    name: Flutter App with Native Liquid Glass (iOS 26)
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      xcode: 26.1
      flutter: stable
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
      cancel_previous_builds: true
    
    scripts:
      - name: Show Xcode and Flutter version
        script: |
          xcodebuild -version
          flutter --version
      
      - name: Get Flutter dependencies
        script: |
          cd flutter_app
          flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd flutter_app/ios
          pod install --repo-update
      
      - name: Build Flutter for iOS
        script: |
          cd flutter_app
          flutter build ios --release --no-codesign --config-only
      
      - name: Archive with xcodebuild
        script: |
          cd flutter_app/ios
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -archivePath ../build/Runner.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            SKIP_INSTALL=NO
      
      - name: Export Unsigned IPA
        script: |
          cd flutter_app/build
          mkdir -p Payload
          cp -r Runner.xcarchive/Products/Applications/Runner.app Payload/
          zip -r FlutterApp-iOS26-unsigned.ipa Payload
    
    artifacts:
      - flutter_app/build/FlutterApp-iOS26-unsigned.ipa
      - flutter_app/build/Runner.xcarchive
